spring:
  datasource:
    driver-class-name: org.postgresql.Driver
message:
  report_time_in_hours: 24
  titles_count_limit: 5
  report_completed_cron: 0 0 0 * * *
  report_not_completed_cron: 0 0 0 * * *