spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - app_data