name: docker hub deploy
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: build with Maven
        run: mvn -B package --file pom.xml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build-push task-tracker-api
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aleksandrkamen/task-tracker-api:latest
          build-args: JAR_FILE=task-tracker-api/target/task-tracker-api-0.0.1-SNAPSHOT.jar
      - name: build-push task-tracker-email-sender
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aleksandrkamen/task-tracker-email-sender:latest
          build-args: JAR_FILE=task-tracker-email-sender/target/task-tracker-email-sender-0.0.1-SNAPSHOT.jar
      - name: build-push task-tracker-frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aleksandrkamen/task-tracker-frontend:latest
          build-args: JAR_FILE=task-tracker-frontend/target/task-tracker-frontend-0.0.1-SNAPSHOT.jar
      - name: build-push task-tracker-scheduler
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aleksandrkamen/task-tracker-scheduler:latest
          build-args: JAR_FILE=task-tracker-scheduler/target/task-tracker-scheduler-0.0.1-SNAPSHOT.jar
